### ISSUE TITLE
A warning using openmpi on MacOS

### ISSUE THREAD

**Issue by nsccwx-hx** [hxmhuang/OpenArray#21]
I used openmpi to compile OpenArray on MacOS, it appeared some waring shown as below:

![warning_of_openarray_macos_openmpi](https://user-images.githubusercontent.com/22727295/63830168-11133d00-c99e-11e9-8c1b-f77c0c8524f3.jpg)

**Comment by xinghuang2050** [comment]
Since the ar and ranlib on MacOS are different from their version in GNU, the warnings occur. However, these warings won't affect the installation of OpenArray.
